- modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
- modules/library/src/test/scala/zio/elasticsearch/QueryDSLSpec.scala
> (dsl): Support filter criteria in bool compound query

- modules/example/src/main/scala/example/api/Criteria.scala
- modules/example/src/main/scala/example/api/Repositories.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
- modules/library/src/test/scala/zio/elasticsearch/QueryDSLSpec.scala
Resolves https://github.com/lambdaworks/zio-elasticsearch/issues/62
> Support MustNot in Bool compound query and add tests

- .github/workflows/ci.yml
- modules/example/src/main/scala/example/RepositoriesElasticsearch.scala
- modules/example/src/main/scala/example/api/HealthCheck.scala
- modules/example/src/main/scala/example/package.scala
- modules/library/src/it/scala/zio/elasticsearch/IntegrationSpec.scala
- modules/library/src/main/scala/zio/elasticsearch/Elasticsearch.scala
- modules/library/src/main/scala/zio/elasticsearch/executor/HttpExecutor.scala
- modules/library/src/main/scala/zio/elasticsearch/package.scala
- modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
- modules/library/src/main/scala/zio/elasticsearch/query/ScoreMode.scala
- modules/library/src/main/scala/zio/elasticsearch/query/sort/Missing.scala
- modules/library/src/main/scala/zio/elasticsearch/query/sort/NumericType.scala
- modules/library/src/main/scala/zio/elasticsearch/query/sort/SortMode.scala
- modules/library/src/main/scala/zio/elasticsearch/query/sort/SortOrder.scala
- modules/library/src/test/scala/zio/elasticsearch/HttpElasticExecutorSpec.scala
- modules/library/src/test/scala/zio/elasticsearch/IndexNameSpec.scala
- modules/library/src/test/scala/zio/elasticsearch/QueryDSLSpec.scala
- project/BuildHelper.scala
> Support Scala 3

- modules/example/src/main/scala/example/RepositoriesElasticsearch.scala
- modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
- modules/library/src/main/scala/zio/elasticsearch/executor/HttpExecutor.scala
- modules/library/src/main/scala/zio/elasticsearch/request/package.scala
> (api): Support `from` and `size` pagination parameters

- modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
- modules/library/src/it/scala/zio/elasticsearch/IntegrationSpec.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
- modules/library/src/main/scala/zio/elasticsearch/InnerHits.scala
- modules/library/src/main/scala/zio/elasticsearch/executor/HttpExecutor.scala
- modules/library/src/main/scala/zio/elasticsearch/executor/response/InnerHitsResponse.scala
- modules/library/src/main/scala/zio/elasticsearch/executor/response/SearchWithAggregationsResponse.scala
- modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
- modules/library/src/main/scala/zio/elasticsearch/query/package.scala
- modules/library/src/main/scala/zio/elasticsearch/result/ElasticResult.scala
- modules/library/src/main/scala/zio/elasticsearch/result/Item.scala
- modules/library/src/test/scala/zio/elasticsearch/QueryDSLSpec.scala
> (dsl): Support inner hits

- modules/example/src/main/scala/example/RepositoriesElasticsearch.scala
- modules/example/src/main/scala/example/api/Repositories.scala
- modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
- modules/library/src/main/scala/zio/elasticsearch/executor/HttpExecutor.scala
- modules/library/src/main/scala/zio/elasticsearch/request/CreationOutcome.scala
- modules/library/src/main/scala/zio/elasticsearch/request/DeletionOutcome.scala
- modules/library/src/main/scala/zio/elasticsearch/request/Document.scala
- modules/library/src/main/scala/zio/elasticsearch/request/UpdateOutcome.scala
- modules/library/src/test/scala/zio/elasticsearch/ElasticRequestsDSLSpec.scala
- modules/library/src/test/scala/zio/elasticsearch/HttpElasticExecutorSpec.scala
- modules/library/src/test/scala/zio/elasticsearch/SttpBackendStubSpec.scala
> (dsl): Support Update request

- modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticHighlight.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticSort.scala
- modules/library/src/main/scala/zio/elasticsearch/Elasticsearch.scala
- modules/library/src/main/scala/zio/elasticsearch/Field.scala
- modules/library/src/main/scala/zio/elasticsearch/aggregation/package.scala
- modules/library/src/main/scala/zio/elasticsearch/highlights/Highlights.scala
- modules/library/src/main/scala/zio/elasticsearch/package.scala
- modules/library/src/main/scala/zio/elasticsearch/query/package.scala
- modules/library/src/main/scala/zio/elasticsearch/query/sort/package.scala
- modules/library/src/main/scala/zio/elasticsearch/request/package.scala
- modules/library/src/main/scala/zio/elasticsearch/script/package.scala
> Add `Scaladoc` to public API

- modules/example/src/main/scala/example/RepositoriesElasticsearch.scala
- modules/example/src/main/scala/example/api/Repositories.scala
- modules/example/src/main/scala/example/api/package.scala
- modules/example/zio-elasticsearch-example.postman_collection.json
> (example): Support `offset` and `limit` query parameters

- modules/library/src/main/scala/zio/elasticsearch/ElasticConfig.scala
Not sure if that's enough, but it's a start
Resolves #202
> Add SSL support

- modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
- modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
- modules/library/src/main/scala/zio/elasticsearch/aggregation/options/HasSize.scala
- modules/library/src/main/scala/zio/elasticsearch/executor/HttpExecutor.scala
- modules/library/src/main/scala/zio/elasticsearch/executor/response/AggregationResponse.scala
- modules/library/src/main/scala/zio/elasticsearch/query/sort/Sort.scala
- modules/library/src/test/scala/zio/elasticsearch/ElasticAggregationSpec.scala
Resolves bucketSortPipelineAgg in #118
> (dsl): Support 'bucketSortPipeline' aggregation

- modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
- modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
- modules/library/src/main/scala/zio/elasticsearch/script/Script.scala
- modules/library/src/main/scala/zio/elasticsearch/script/options/HasParams.scala
- modules/library/src/test/scala/zio/elasticsearch/ElasticAggregationSpec.scala
- modules/library/src/test/scala/zio/elasticsearch/ElasticRequestDSLSpec.scala
- modules/library/src/test/scala/zio/elasticsearch/HttpElasticExecutorSpec.scala
- modules/library/src/test/scala/zio/elasticsearch/ScriptSpec.scala
- modules/library/src/test/scala/zio/elasticsearch/SortSpec.scala
Resolves bucketSelectorPipelineAgg in #118
> (dsl): Support 'bucketSelectorPipeline' aggregation

- website/docusaurus.config.js
- website/package.json
Fix this [issue](https://github.com/lambdaworks/zio-elasticsearch/issues/249).
> (website) Update libraries and requires

- modules/library/src/test/scala/zio/elasticsearch/FieldDSLSpec.scala
Description:
- Refactor FieldDSLSpec
Part of #251
> Refactor FieldDSLSpec

- build.sbt
- modules/example/src/main/scala/example/Main.scala
- modules/example/src/main/scala/example/config/AppConfig.scala
> Update zio-config to 4.0.1

- .github/workflows/ci.yml
- project/BuildHelper.scala
> Update Scala to 3.3.3

- .github/workflows/ci.yml
- project/BuildHelper.scala
> Update Scala to 3.4.1

- website/package.json
> Update Docusaurus to 3.2.0

- website/package.json
> Update Docusaurus to 3.2.1

- website/package.json
> Bump docusaurus versions

- .github/workflows/ci.yml
- project/BuildHelper.scala
> Bump Scala 3.4.1 to 3.4.2

- build.sbt
- modules/example/src/main/scala/example/Main.scala
- modules/example/src/main/scala/example/external/github/RepoFetcher.scala
- modules/integration/src/test/scala/zio/elasticsearch/IntegrationSpec.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticExecutor.scala
- modules/library/src/main/scala/zio/elasticsearch/executor/HttpExecutor.scala
- modules/library/src/test/scala/zio/elasticsearch/SttpBackendStubSpec.scala
- Bump `zio` version from `2.0.22` to `2.1.1`
- Bump `sttp` client from version `3.9.6` to `4.0.0-M14`
- Closes #434 
- Closes #435
> Bump STTP client v3 to v4

- website/package.json
> Bump docusaurus to 3.5.1

- build.sbt
- modules/example/src/main/scala/example/Main.scala
- modules/example/src/main/scala/example/api/HealthCheck.scala
- modules/example/src/main/scala/example/api/Repositories.scala
- modules/example/src/main/scala/example/api/package.scala
> Update zio-http to 3.0.0

- .github/workflows/ci.yml
- project/BuildHelper.scala
> Bump Scala version to 3.5.1

- build.sbt
- modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
> Update zio-schema, zio-schema-json to 1.5.0

- .github/workflows/ci.yml
- project/BuildHelper.scala
> Update Scala to 3.5.2

- build.sbt
> Update sttp client's zio & zio-json to 4.0.0-M19 

- website/package.json
> Update website lib versions

- .github/workflows/ci.yml
- project/BuildHelper.scala
> Bump Scala 3.5.2 to Scala 3.6.2

- project/plugins.sbt
> Bump sbt-ci-release to 1.9.2

- .github/workflows/ci.yml
- project/BuildHelper.scala
> Bump Scala 3.6.2 to 3.6.3

- build.sbt
> Bump ZIO schema to 1.6.1

- build.sbt
- modules/library/src/main/scala/zio/elasticsearch/executor/HttpExecutor.scala
> Bump STTP client to 4.0.0-M25

- build.sbt
- modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
> Update zio-json to 0.7.21

- build.sbt
- modules/library/src/test/scala/zio/elasticsearch/SttpBackendStubSpec.scala
> Update STTP client to 4.0.0-RC1

- .github/workflows/ci.yml
- project/BuildHelper.scala
> Bump Scala 3.6.3 to 3.6.4

- build.sbt
- modules/example/src/main/scala/example/api/Repositories.scala
- modules/library/src/main/scala/zio/elasticsearch/result/Item.scala
> Update zio-schema to 1.7.0

- .github/workflows/ci.yml
- project/BuildHelper.scala
> Bump Scala 3.6.4 to Scala 3.7.0

- build.sbt
> Bump zio-schema to 1.7.1

- .github/workflows/ci.yml
- project/BuildHelper.scala
> Bump Scala 3.7.0 to 3.7.1

- modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
- modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
- modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
- modules/library/src/main/scala/zio/elasticsearch/executor/response/AggregationResponse.scala
- modules/library/src/main/scala/zio/elasticsearch/executor/response/SearchWithAggregationsResponse.scala
- modules/library/src/main/scala/zio/elasticsearch/package.scala
- modules/library/src/main/scala/zio/elasticsearch/result/AggregationResult.scala
- modules/library/src/test/scala/zio/elasticsearch/ElasticAggregationSpec.scala
> (dsl): Support Sampler aggregation
