lambdaworks/zio-elasticsearch

modules/library/src/main/scala/zio/elasticsearch/Boost.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/test/scala/zio/elasticsearch/QueryDSLSpec.scala

Support boost in Range and Bool query

---

modules/example/src/main/scala/example/Main.scala
modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/it/scala/zio/elasticsearch/IntegrationSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
modules/library/src/test/scala/zio/elasticsearch/HttpElasticExecutorSpec.scala

Instead of having one public method for creating index - `def createIndex(name: IndexName, definition: Option[String])`, I separated that into two methods, avoiding `Option`. 
```
def createIndex(name: IndexName)
def createIndex(name: IndexName, definition: String)
```

(dsl): Provide `createIndex` methods

---

modules/example/src/main/scala/example/RepositoriesElasticsearch.scala
modules/example/src/main/scala/example/api/Repositories.scala
modules/library/src/main/scala/zio/elasticsearch/Boost.scala
modules/library/src/main/scala/zio/elasticsearch/CaseInsensitive.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
modules/library/src/main/scala/zio/elasticsearch/Field.scala
modules/library/src/main/scala/zio/elasticsearch/IgnoreUnmapped.scala
modules/library/src/main/scala/zio/elasticsearch/ScoreMode.scala
modules/library/src/test/scala/zio/elasticsearch/QueryDSLSpec.scala

(dsl): Support Nested query

---

docs/overview/queries/elastic_query_match_phrase.md
modules/example/src/main/scala/example/api/ErrorResponse.scala
modules/example/src/main/scala/example/api/ErrorResponseData.scala
modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/test/scala/zio/elasticsearch/QueryDSLSpec.scala
website/sidebars.js

Resolves `matchPhraseQuery` in #91
- Provided `matchPhrase` query. 
- Provided `boost` options both for `match` and `matchPhrase` queries.
- Addressed warning for the example app.
- Improved documentation (provided .). 
- Changed the way of constructing fields in `paramsToJson` methods.
- Adapted existing and provided new tests.
- Provided structure for the website.

(dsl): Support 'matchPhrase' query

---

modules/library/src/main/scala/zio/elasticsearch/ElasticPrimitive.scala
modules/library/src/test/scala/zio/elasticsearch/AggregationSpec.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticPrimitiveSpec.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticPrimitivesSpec.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticRequestDSLSpec.scala
modules/library/src/test/scala/zio/elasticsearch/FieldDSLSpec.scala
modules/library/src/test/scala/zio/elasticsearch/HighlightsSpec.scala
modules/library/src/test/scala/zio/elasticsearch/HttpElasticExecutorSpec.scala
modules/library/src/test/scala/zio/elasticsearch/IndexNameSpec.scala
modules/library/src/test/scala/zio/elasticsearch/QueryDSLSpec.scala

Summary: 
- Introduce Elastic Primitive for java.UUID
- Add tests for creating query with each Elastic Primitive

Support Elastic primitive for UUID

---

modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/main/scala/zio/elasticsearch/query/package.scala
modules/library/src/test/scala/zio/elasticsearch/QueryDSLSpec.scala

- Added `minimumShouldMatch` support for `BoolQuery`.
- Made the `paramsToJson` and `toJson` methods as package private.
- Formatted code.
- Adapted tests to check whether `minimumShouldMatch` is successfully set.

Support `minimumShouldMatch` on BoolQuery

---

docs/overview/queries/elastic_query_has_parent.md
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/query/InnerHits.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/test/scala/zio/elasticsearch/QueryDSLSpec.scala
website/sidebars.js

Resolves `hasParentQuery` in #91 
Summary: 
- Added has parent query
- Added tests for has parent query

(dsl): Add has parent query

---

modules/library/src/it/scala/zio/elasticsearch/IntegrationSpec.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticRequestDSLSpec.scala
modules/library/src/test/scala/zio/elasticsearch/QueryDSLSpec.scala
modules/library/src/test/scala/zio/elasticsearch/SttpBackendStubSpec.scala
modules/library/src/test/scala/zio/elasticsearch/domain/TestDocument.scala

- Renamed `QueryDSLSpec` to `ElasticQuerySpec`. 
- Group all tests to related query - `bool`, `matches`, `matchAll`, etc. 
- Use simpler naming in tests.

Refactor ElasticQuery tests

---

modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticPrimitive.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala

(dsl): Support LocalDate elastic primitive and date format for range queries

---

modules/example/src/main/scala/example/RepositoriesElasticsearch.scala
modules/example/src/main/scala/example/api/Criteria.scala
modules/example/src/main/scala/example/external/github/RepoFetcher.scala
modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala-2/zio/elasticsearch/IndexNameValidation.scala
modules/library/src/main/scala-3/zio/elasticsearch/IndexNameValidator.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
modules/library/src/main/scala/zio/elasticsearch/Field.scala
modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
modules/library/src/main/scala/zio/elasticsearch/executor/HttpExecutor.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/AggregationResponse.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/BulkResponse.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/Hits.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/SearchWithAggregationsResponse.scala
modules/library/src/main/scala/zio/elasticsearch/highlights/Highlights.scala
modules/library/src/main/scala/zio/elasticsearch/query/InnerHits.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/main/scala/zio/elasticsearch/query/sort/Sort.scala
modules/library/src/main/scala/zio/elasticsearch/request/options/HasSourceFiltering.scala
modules/library/src/main/scala/zio/elasticsearch/result/ElasticResult.scala
modules/library/src/main/scala/zio/elasticsearch/result/Item.scala
modules/library/src/main/scala/zio/elasticsearch/script/Script.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticAggregationSpec.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
modules/library/src/test/scala/zio/elasticsearch/HttpElasticExecutorSpec.scala
modules/library/src/test/scala/zio/elasticsearch/SortSpec.scala

Replace List with Chunk

---

modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/main/scala/zio/elasticsearch/query/sort/Sort.scala
modules/library/src/main/scala/zio/elasticsearch/request/options/HasHighlights.scala
modules/library/src/main/scala/zio/elasticsearch/request/options/HasSearchAfter.scala
modules/library/src/main/scala/zio/elasticsearch/request/options/HasSourceFiltering.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticRequestSpec.scala

1. Added missing `scaladoc` for public methods
2. Refactor source filtering in ElasticRequest and add type-safety
3. Make toJson method private[elasticsearch]
4. Move certain methods from requests to separated traits (search after and highlights)
5. Other small changes

Refactor core and add missing scaladoc

---

modules/library/src/main/scala/zio/elasticsearch/executor/HttpExecutor.scala
modules/library/src/main/scala/zio/elasticsearch/query/Distance.scala

This PR resolves issues #221 and #154.

(fix): Resolve minor issues

---

modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
modules/library/src/test/scala/zio/elasticsearch/ScriptSpec.scala

(dsl): Support script query

---

docs/overview/queries/elastic_query_bool.md
docs/overview/queries/elastic_query_range.md
docs/overview/queries/elastic_query_term.md
docs/overview/queries/elastic_query_terms.md
docs/overview/queries/elastic_query_wildcard.md
docs/overview/requests/elastic_request_aggregate.md
docs/overview/requests/elastic_request_bulk.md
docs/overview/requests/elastic_request_count.md
docs/overview/requests/elastic_request_create.md
docs/overview/requests/elastic_request_create_index.md
docs/overview/requests/elastic_request_delete_by_id.md
docs/overview/requests/elastic_request_delete_by_query.md
docs/overview/requests/elastic_request_delete_index.md
docs/overview/requests/elastic_request_exists.md
docs/overview/requests/elastic_request_get_by_id.md
docs/overview/requests/elastic_request_search.md
docs/overview/requests/elastic_request_update.md
docs/overview/requests/elastic_request_update_by_query.md
docs/overview/requests/elastic_request_upsert.md
modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
website/sidebars.js

Add website documentation for requests

---

modules/library/src/test/scala/zio/elasticsearch/ScriptSpec.scala

Description:
- Refactor ScriptSpec
Part of #251

Refactor ScriptSpec

---

modules/library/src/test/scala/zio/elasticsearch/ScriptSpec.scala

Description:
- Improve ScriptSpec refactor
Part of #251

(tests): Restructure ScriptSpec

---

modules/library/src/test/scala/zio/elasticsearch/HighlightsSpec.scala

(tests): Restructure HighlightsSpec

---

docs/overview/aggregations/elastic_aggregation_missing.md
modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/AggregationResponse.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/SearchWithAggregationsResponse.scala
modules/library/src/main/scala/zio/elasticsearch/package.scala
modules/library/src/main/scala/zio/elasticsearch/result/AggregationResult.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticAggregationSpec.scala
website/sidebars.js

(dsl): Support `missing` aggregation

---

modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/test/scala/zio/elasticsearch/HttpElasticExecutorSpec.scala

- Move the `ids` query to sort it properly.
- Adapt return types for `ElasticQuery`.
- Reformat `HttpElasticExecutorSpec`.

Reorganize ElasticQuery

---

docs/overview/queries/elastic_query_match_phrase_prefix.md
modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
website/sidebars.js

(dsl): Support `matchPhrasePrefix` query

---

docs/overview/queries/elastic_query_regexp.md
modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
website/sidebars.js

(dsl): Support `regexp` query

---

docs/overview/queries/elastic_query_match_boolean_prefix.md
modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
website/sidebars.js

(dsl): Support `matchBooleanPrefix` query

---

docs/overview/aggregations/elastic_aggregation_percentiles.md
modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/AggregationResponse.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/SearchWithAggregationsResponse.scala
modules/library/src/main/scala/zio/elasticsearch/package.scala
modules/library/src/main/scala/zio/elasticsearch/result/AggregationResult.scala
modules/library/src/main/scala/zio/elasticsearch/result/ElasticResult.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticAggregationSpec.scala
website/sidebars.js

Add support for percentiles aggregation

---

docs/overview/queries/elastic_query_constant_score.md
modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
website/sidebars.js

(dsl): Support `constantScore` query

---

docs/overview/queries/elastic_query_disjunction_max.md
modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticPrimitive.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
website/sidebars.js

Part of https://github.com/lambdaworks/zio-elasticsearch/issues/91

(dsl): Support `Disjunction max` query

---

docs/overview/aggregations/elastic_aggregation_filter.md
modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
modules/library/src/main/scala/zio/elasticsearch/executor/HttpExecutor.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/AggregationResponse.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/SearchWithAggregationsResponse.scala
modules/library/src/main/scala/zio/elasticsearch/result/AggregationResult.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticAggregationSpec.scala
website/sidebars.js

Part of https://github.com/lambdaworks/zio-elasticsearch/issues/118

(dsl): Support `Filter` aggregation

---

docs/overview/aggregations/elastic_aggregation_percentile_ranks.md
modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/AggregationResponse.scala
modules/library/src/main/scala/zio/elasticsearch/executor/response/SearchWithAggregationsResponse.scala
modules/library/src/main/scala/zio/elasticsearch/package.scala
modules/library/src/main/scala/zio/elasticsearch/result/AggregationResult.scala
modules/library/src/main/scala/zio/elasticsearch/result/ElasticResult.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticAggregationSpec.scala
website/sidebars.js

Part of https://github.com/lambdaworks/zio-elasticsearch/issues/118

(dsl): Support `Percentile ranks` aggregation

---

docs/overview/queries/elastic_query_geo_polygon.md
modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
modules/integration/src/test/scala/zio/elasticsearch/IntegrationSpec.scala
modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
website/sidebars.js

(dsl): Support `geoPolygon` query
